---
- name: Grafana | Install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Grafana | Add grafana gpg key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: false

- name: Grafana | Add grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    validate_certs: false

- name: Grafana | Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Grafana | Start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: true

- name: Grafana | Wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Grafana | Change admin password for Grafana gui
  command: "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

- name: Grafana | Create/Update datasources file (provisioning)
  become: true
  copy:
    dest: "/etc/grafana/provisioning/datasources/ansible.yml"
    content: |
      apiVersion: 1
      deleteDatasources: []
      datasources:
      {{ grafana_datasources | to_nice_yaml }}
    backup: false
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana

- name: Grafana | Dashboard configure
  import_tasks: dashboard.yml
