---
- name: Prometheus | Create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: Prometheus | Create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin" # You will not be able to login to this user
    group: prometheus
    createhome: false
    home: "{{ prometheus_db_dir }}"

- name: Prometheus | Create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Prometheus | Create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- name: Prometheus | Download prometheus binaries to temp folder(locally)
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.36.2.linux-amd64.tar.gz"
    mode: 0664
  delegate_to: localhost
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: Prometheus | Unpack prometheus binaries(locally)
  unarchive:
    src: "/tmp/prometheus-2.36.2.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-2.36.2.linux-amd64/prometheus"
  delegate_to: localhost

- name: Prometheus | Propagate official prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-2.36.2.linux-amd64/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: Prometheus | Propagate official console templates
  copy:
    src: "/tmp/prometheus-2.36.2.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: root
    group: root
  with_items:
    - console_libraries
    - consoles
  notify:
    - restart prometheus

- name: Prometheus | Create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus

- name: Alerting rules file
  template:
    src: "templates/alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_binary_install_dir }}/promtool check rules %s"
  notify:
    - reload prometheus

- name: Prometheus | Configure prometheus
  template:
    src: "prometheus.j2"
    dest: "/etc/prometheus/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_binary_install_dir }}/promtool check config %s"
  notify:
    - reload prometheus

- name: Ensure prometheus is started
  systemd:
    name: prometheus
    state: started
    enabled: true

    
