---
- name: Letsencrypt | Check if certificate already exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ virtual_domain }}/cert.pem"
  register: letsencrypt_cert


- name: Letsencrypt | Generate new certificate
  shell: >
    certbot certonly --nginx --email '{{ letsencrypt_email }}'
    --agree-tos --no-eff-email -d '{{ virtual_domain }}'
    -d 'www.{{ virtual_domain }}' -d 'gitlab.{{ virtual_domain }}'
    -d 'grafana.{{ virtual_domain }}' -d 'prometheus.{{ virtual_domain }}'
    -d 'alertmanager.{{ virtual_domain }}'
  when: not letsencrypt_cert.stat.exists

    #- name: Letsencrypt | Force renew certificate
    #  shell: >
    #    certbot certonly --nginx --force-renew --email '{{ letsencrypt_email }}'
    #    --agree-tos --no-eff-email -d '{{ virtual_domain }}'
    #    -d 'www.{{ virtual_domain }}' -d 'gitlab.{{ virtual_domain }}'
    #    -d 'grafana.{{ virtual_domain }}' -d 'prometheus.{{ virtual_domain }}'
    #    -d 'alertmanager.{{ virtual_domain }}'
    #  ignore_errors: true 
